name: "Release PDF"
description: "Release the previously created PDF"
inputs:
  title:
    description: The title of the document
    required: true
    default: "Feladat neve"
  subtitle:
    description: The title of the document
    required: true
    default: "Programozás"
  author:
    description: The author of the document
    required: true
    default: "Ignácz Dominik Bence"
  files:
    description: The files to create the PDF from
    required: true
    default: "README.md"
  artifact-name: 
    description: 'How to save the artifact'
    required: true
    default: 'Tananyag'
  pdf-path:
    description: 'Where the PDF is stored'
    required: true
    default: './build/frontend.pdf'
  gh_token:
    description: 'Token used for login'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Save "README.md"
      shell: bash
      run: mkdir save && mv README.md save/README.md
    - name: Get PDF-assets
      shell: bash
      run: wget https://github.com/ignaczdominik/pdf-assets/archive/refs/tags/v1.zip
    - name: Unpack PDF-assets
      shell: bash
      run: unzip v1.zip && mv pdf-assets-1/* . && rm -rf pdf-assets-1 && rm README.md
    - name: Restore "README.md"
      shell: bash
      run: mv save/README.md README.md && rm -rf save
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ inputs.gh_token}}
    - name: Check files
      shell: bash
      run: ls -l .
    - name: Create Artifacts
      uses: ignaczdominik/pdf-assets@v1
      with:
        title: ${{ inputs.title }}
        subtitle: ${{ inputs.subtitle }}
        version: ${{ steps.tag_version.outputs.new_tag }}
        author: ${{ inputs.author }}
        files: ${{ inputs.files }}
    - name: Check files
      shell: bash
      run: ls -l .
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.pdf-path }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1.11.2
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        files: ${{ inputs.pdf-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
