name: "Release PDF"
description: "Release the previously created PDF"
inputs:
  artifact-name: 
    description: 'How to save the artifact'
    required: true
    default: 'Tananyag'
  pdf-path:
    description: 'Where the PDF is stored'
    required: true
    default: './build/frontend.pdf'
  github-token:
    required: true
runs:
  using: "composite"
  steps:
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.pdf-path }}
    - name: Get version
      shell: bash
      run: echo version=`grep -Eo '[0-9]\.[0-9]\.[0-9]+' pdf-assets/metadata.yml` >> $GITHUB_ENV
      id: version
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ inputs.github-token }}
        custom_tag: ${{ env.version }}
    - name: Create a GitHub release
      uses: ncipollo/release-action@v1.11.2
      with:
        tag: ${{ steps.tag_version.outputs.new_tag }}
        name: Release ${{ steps.tag_version.outputs.new_tag }}
    - name: Release
      uses: softprops/action-gh-release@v0.1.14
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        files: ${{ inputs.pdf-path }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
